language: php

php:
  - 7.x

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  include:
    - php: 7.x
      env: 'COMPOSER_FLAGS="--prefer-stable"'

before_script:
  - composer dump-auto
  - mv example.phpunit.xml.dist phpunit.xml.dist
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit tests

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
